search_test.go

1. remove goroutine in `TestRandomData` and  `TestRandomValidStrings` to avoid data-race
2. reduce loop times in `TestRandomMany` to avoid timeout

fix: avoid search_test UT data-race and timeout

---

encoder/assembler_amd64.go
encoder/stubs.go
encoder/types.go
internal/rt/fastvalue.go

Benchmark shows it improves encoding performance about 4.7%.

feat: reduce allocs for mapiterinit

---

decode_test.go
decoder/generic_amd64.go
decoder/pools.go
issue27_test.go

fix: return error on stack overflow instead of panicking

---

Makefile
decoder/assembler_amd64.go
decoder/generic_amd64.go
encoder/assembler_amd64.go
encoder/assembler_test.go
encoder/encoder.go
encoder/primitives.go
encoder/utils.go
internal/native/avx/native_amd64.go
internal/native/avx/native_amd64.s
internal/native/avx/native_amd64_test.go
internal/native/avx/native_export_amd64.go
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_amd64_test.go
internal/native/avx2/native_export_amd64.go
internal/native/avx2/native_subr_amd64.go
internal/native/dispatch_amd64.go
internal/native/dispatch_amd64.s
internal/native/native_amd64.tmpl
internal/native/native_amd64_test.tmpl
internal/native/native_export_amd64.tmpl
native/fastbytes.c
native/fastint.c
native/native.h
native/parsing.c
native/scanning.c

This boosts performance about 30%.

feat: performance optimizations

---

decoder/assembler_amd64.go
decoder/compiler.go
decoder/errors.go
encoder/compiler.go
encoder/primitives.go
encoder/stubs.go
internal/caching/pcache.go
internal/rt/fastvalue.go
issue39_test.go
issue5_test.go

fix: support dynamic interface indirection

---

encoder/compiler.go
issue58_test.go

fix: fix nil pointer on value receiver (#58)

---

encode_test.go
encoder/assembler_amd64.go
encoder/assembler_test.go
encoder/compiler.go
encoder/encoder.go
encoder/encoder_test.go
encoder/mapiter.go
encoder/pools.go
encoder/primitives.go
encoder/sort.go
encoder/sort_test.go
encoder/stubs.go
encoder/types.go
internal/native/dispatch_amd64.go
internal/native/dispatch_amd64.s
internal/rt/fastvalue.go
sonic.go

Supports map key-sorting as an optional feature that defaults to disabled.
Resolves #24.

feat: supports map key-sorting via encoder options

---

decoder/decoder.go
issue67_test.go
sonic.go

fix: check EOF after unmarshal

---

encoder/assembler_amd64.go
encoder/compiler.go
issue76_test.go

fix: check flags for indirection

---

decoder/assembler_amd64.go
encoder/assembler_amd64.go
go.mod
go.sum

fix: support AVX2 auto-detection for base64x

---

README.md
ast/encode.go
ast/iterator.go
ast/iterator_test.go
ast/node.go
ast/node_test.go
ast/parser.go
ast/parser_test.go
ast/search_test.go
search_test.go

BREAKING CHANGE:
- Set()/Unset()/SetByIndex()/UnsetByIndex/Add() 
- Values()/Properties()/Map()/Array()/Interface() 
- Raw()/Bool()/Int64()/String()/Float64()

chore!: return error for scanning API

---

decoder/assembler_amd64.go
decoder/assembler_test.go
decoder/compiler.go
decoder/pools.go
encoder/assembler_amd64.go
encoder/assembler_test.go
encoder/compiler.go
encoder/pools.go
issue82_test.go

fix: unmarshalers are always addressable

---

decoder/pools.go
encoder/pools.go
internal/caching/fcache.go
internal/caching/pcache.go
internal/caching/pcache_test.go

A lot of threads rushing into the compiler may cause OOM. This PR fixes this problem.

fix: potential ProgramCache OOM under high-load

---

internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
internal/native/types/types.go
issue90_test.go
native/native.h
native/scanning.c

fix: make it return error when unmarshal infinity float number

---

encoder/compiler.go
encoder/mapiter.go
issue98_test.go

fix: defer single-element maps checking

---

decode_test.go
decoder/assembler_amd64.go
decoder/stubs.go
encode_test.go
issue100_test.go

fix(#100): check type-size of map element to decide whether use mapassign_fastxx

---

decoder/assembler_amd64.go
decoder/generic_amd64.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
internal/native/types/types.go
issue100_test.go
issue101_test.go
native/scanning.c

fix: check character range before BTQ

---

internal/native/avx/native_amd64.s
internal/native/avx2/native_amd64.s
issue_test/issue108_test.go
native/scanning.c

fix: skip exponent that begins with zero in skip_number()

---

encoder/mapiter.go
encoder/sort.go
issue_test/issue115_test.go
issue_test/issue8_test.go
issue_test/issue90_test.go

fix: make it sorted when marshalling integer key map

---

decoder/assembler_amd64_go115.go
decoder/assembler_amd64_go116.go
decoder/assembler_amd64_go117.go
decoder/compiler.go
issue_test/issue144_test.go

fix: 'string' option in struct tag as encoding/json

---

ast/encode.go
ast/encode_test.go

```
goversion: 1.16.4
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkEncodeRaw-16            1000000              2157 ns/op        6037.17 MB/s       13579 B/op          1 allocs/op
BenchmarkEncodeSkip-16           1000000              2310 ns/op        5637.77 MB/s       13579 B/op          1 allocs/op
BenchmarkEncodeLoad-16           1000000             13294 ns/op         979.60 MB/s        9478 B/op          1 allocs/op
```

fix:(ast) quote string when `node.MarshalJSON()`

---

decoder/assembler_amd64_go116.go
decoder/assembler_amd64_go117.go
decoder/decoder.go
issue_test/issue186_test.go
sonic.go

fix: premature GC on decoding string

---

ast/node.go
issue_test/issue248_test.go

fix:(ast) checkRaw() check if node is nil pointer first

---

decoder/stream.go
decoder/stream_test.go
issue_test/issue293_test.go

fix:(decoder) `StreamDecoder` unexpectedly stop while skipping incomplete number

---

ast/node.go
ast/search.go

Use type switch eliminate type assertions.

optimize type assertion

---

encoder/assembler_amd64_go116.go
encoder/assembler_amd64_go117.go
issue_test/issue390_test.go

fix: direct struct/array type with marshaler

---

decoder/compiler.go
issue_test/issue390_test.go

fix: unmarshal recursive pointer type

---

internal/resolver/resolver.go
issue_test/issuex403_test.go

fix: incorrectly handle alias type of pointer in struct

---

internal/decoder/assembler_amd64_go116.go
internal/decoder/assembler_amd64_go117.go
internal/jit/assembler_amd64.go

fix: mov lagre imm to mem instruction in jit

---

api.go
api_test.go

Finish https://github.com/bytedance/sonic/issues/462

feat: add Valid() api

---

internal/encoder/stream.go

fix: didn't fully reuse buffer memory

---

ast/api_compat.go
decoder/decoder_compat.go
encoder/encoder_compat.go

chore: update incomptible warning message

---

api.go
encode_test.go
encoder/encoder_native.go
internal/encoder/alg/opts.go
internal/encoder/encoder.go
internal/encoder/vm/vm.go
internal/encoder/x86/assembler_regabi_amd64.go
sonic.go

feat: support marshal Inf/NaN as  with option

---

internal/decoder/optdec/native.go

fix(arm): remove print debug

---

.github/workflows/compatibility_test-windows.yml
.github/workflows/compatibility_test.yml
.github/workflows/unit_test-linux-arm.yml
.github/workflows/unit_test-linux-opt-x64.yml
.github/workflows/unit_test-linux-x64.yml

chore: add Go 1.23 to workflows

---

README_ZH_CN.md

A small typo in README_ZH_CN.md :)

fix: readme typos

---

external_jsonlib_test/go.mod
external_jsonlib_test/go.sum
go.mod
go.sum
go.work.sum

fix: update base64x version to avoid illegal instru in sse

---

internal/native/neon/f32toa_arm64.s
internal/native/neon/f64toa_arm64.s
internal/native/neon/get_by_path_arm64.s
internal/native/neon/parse_with_padding_arm64.s
internal/native/neon/parse_with_padding_subr_arm64.go
internal/native/neon/skip_array_arm64.s
internal/native/neon/skip_array_subr_arm64.go
internal/native/neon/skip_object_arm64.s
internal/native/neon/skip_object_subr_arm64.go
internal/native/neon/skip_one_arm64.s
internal/native/neon/unquote_arm64.s
internal/native/neon/validate_one_arm64.s
internal/native/neon/validate_one_subr_arm64.go
internal/native/neon/value_arm64.s
internal/native/neon/vnumber_arm64.s
scripts/build-arm.sh

fix: not use`X28` register in arm64 of native C

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test-arm64.yml

chore: add issue and pr template

---

internal/decoder/optdec/compiler.go
internal/decoder/optdec/map.go
issue_test/issue739_test.go
issue_test/issue744_test.go
issue_test/issue747_test.go

fix
支持JSON 解析为 key 是浮点数的map
en: 
zh(optional): 
Fixed #747

fix(aarch64): support parse map that key is float

---

decode_test.go
internal/decoder/optdec/slice.go
issue_test/common_test.go
issue_test/issue750_test.go

fix #750 
修复解析到非空 []interface{} 的bug
en: 
zh(optional):

fix(aarch64): bug when unmarshal into prefilled interface slice

---

README.md
README_ZH_CN.md
internal/encoder/omitzero_test.go

chore: add notice for go1.24.0 on README

---

external_jsonlib_test/go.mod
external_jsonlib_test/go.sum
generic_test/go.mod
generic_test/go.sum
go.mod
go.sum
go.work.sum

Fix
en: 
zh(optional): 
Fixes #768  Fixes #769

fix: loader version

---

decode_test.go
internal/decoder/jitdec/assembler_regabi_amd64.go
internal/decoder/jitdec/compiler.go
internal/decoder/optdec/interface.go
internal/decoder/optdec/node.go
internal/decoder/optdec/slice.go
issue_test/common_test.go
issue_test/issue379_test.go
issue_test/issue758_test.go
issue_test/issue762_test.go
issue_test/issue772_test.go
issue_test/issue774_test.go

fix
en: 
zh(optional): 
Main Changes as the commit order:
1. Fix the bug when parsing `null`  into non-indirected interface value, (TODO: the jit parts is still hard to fix)
2. Fix #774, parse `"` as empty []byte
3. Fix #772, when found the nil iface type, will skip the json value and still parse the remaining fields as encoding/json
Fixes #772  Fixes #774

fix bug when parsing into nil iface type

---

internal/decoder/optdec/compiler.go
internal/decoder/optdec/map.go
issue_test/common_test.go
issue_test/issue777_test.go

fix
en: 
zh(optional): 
Fixes #777

fix(aarch64): unmarshal into json number slice

---

.gitmodules

Add lacking fuzz/go-fuzz-corpus submodule to https://github.com/dvyukov/go-fuzz-corpus
en: 
zh(optional):

fix(git): add lacking fuzz/go-fuzz-corpus submodule

---

internal/encoder/alg/mapiter.go
issue_test/issue115_test.go

fix
en:  make sure we can marshal `map[bool]` in generic type 
zh(optional):

fix: not panic when marshal map key that is bool

---

compat.go
compat_test.go

fix
en: 
zh(optional): 
Fixes #797

fix(compat): should return error when unmarshaling json with trailing chars

---

internal/encoder/alg/mapiter.go
issue_test/issue824_test.go

en: 
zh(optional): 
Fixes #824

fix(encoder): not panic for unsupported map-key type

---

encoder/encoder_native.go

doc: comments documenting declarations mismatch
文档注释修改，部分注释的声明与主体不匹配，此处是全局变量的变量名称
修改内容位于 /encoder/encoder_native.go

doc: comments documenting declarations mismatch

---

internal/decoder/jitdec/compiler.go
issue_test/issue860_test.go

fix:(decoder) not panic when map key is a interface
