bytedance/sonic

README.md
ast/iterator_test.go
ast/node.go
ast/node_test.go
ast/parser.go
ast/parser_test.go
ast/search.go
ast/search_test.go

1. Decode numeric values into `V_NUMBER`, instead of `native.V_INTEGER/V_DOUBLE`
2. Interface{} is casted to `float64` by default.
3. Add `InterfaceUseNumber()\MapUseNumber()\ArrayUseNumber()\LoadsUseNumber()` to cast `interface{}` to  `json.Number`

feat: support json.Number for ast

---

decoder/assembler_amd64.go
issue27_test.go

fix: use `cap` to check slice emptiness.

---

decoder/stubs.go
encoder/stubs.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
native/scanning.c

Fix: Generic decoder occationally crashes on "found pointer to free object".
It turned out to be a technique I implemented to avoid an allocation for string, called "string packing", it basically appends the string content right after the string header without allocating another block of memory, if the decoder has a prior knowledge to the string length.
The `Data` pointer in the string header points right after the header itself, like this:
```
╔══════════════════╗
0x00000000  ║   string->Data   ║ ───╮
╠══════════════════╣    │
0x00000008  ║   string->Size   ║    │
╠══════════════════╣    │
0x00000010  ║                  ║ <──╯
...     ~      <Data>      ~
...     ║                  ║
╚══════════════════╝
```
But if the string length is `0`, `string->Data` will be pointing to an area …

fix: fix addressing past valid memory for empty string

---

decoder/pools.go
internal/caching/pcache.go
internal/caching/pcache_test.go
issue45_test.go

1. self memory copy at first when `_ProgramMap.insert()`
2. add mux to avoid `fieldCache` racing when `decoder.freezeFields()`

fix:  copy _ProgramMap when RCU write. Fixes #45

---

decode_float_test.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
native/atof_native.c
native/scanning.c

Support high-precision and robust float parsing like Go encoding/json, such as:
1, Special exponents, e.g. "0e123" -> 0, "1e-123456789" (exponent overflow) -> 0;
2, Long mantissa, e.g. "2.222....2222e+1" -> 22.22222222222222.

fix: enhance float parsing as Go encoding/json

---

.gitignore
ast/iterator.go
ast/node.go
ast/node_test.go
ast/parser.go
ast/parser_test.go
bench.sh
search_test.go

- add `Node.Unset()/UnsetByIndex()` API
- adjust the implementation of `Node.Index()/Get()` to support indexing children of object-type node, and use `skip()` instead of `decodeValue()` while loading sub-nodes
- according to benchmark, Node.Get() speeds up about 30%

feat(ast): support Node.Unset() and optimize sub-node traversal

---

ast/node.go
ast/node_test.go
bench.sh

- inline `findkey()`
- use std `append(`) instead of `runtime.memmove()` for `Node.Add()`
- Add `Node.IndexPair()/Node.IndexOrGet()`

opt(ast): speed up Node api

---

internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
native/atof_eisel_lemire.c
native/atof_native.c
native/native.h
native/scanning.c

Origin check prefix function `prefix_cmp` in atof_native.c  has bug, and this commit fixs it.

fix: check prefix in native float parsing

---

decoder/assembler_amd64.go
decoder/generic_amd64.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
issue83_test.go
native/parsing.c

fix: handling of surrogate-half characters within double-quoted strings

---

internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
issue_test/issue107_test.go
native/parsing.c

fix: make it parse the UTF-16 surrogate pair after an invalid unicode

---

encoder/assembler_amd64.go
encoder/compiler.go
encoder/primitives.go
issue_test/issue113_test.go

fix: marshal struct field with "omitempty" tag as encoding/json

---

go.mod
go.sum
issue_test/issue112_test.go

fix: make it return error when unmarshalling invalid base64-encoded strings

---

decoder/assembler_amd64.go
decoder/errors_test.go
decoder/generic_amd64.go
decoder/pools.go

1. Set `p.sp = 0` in `freeStack()`
2. Add `_Decoder_Generic_Shadow()` faker func for `_Decoder_Generic()`, to keep `st` noticeable to GC.

fix: set _Stack.sp zero whenever put into pool

---

.github/workflows/push-check-go115.yml
.github/workflows/push-check-go116.yml
decoder/assembler_amd64_go115.go
decoder/assembler_amd64_go116.go
decoder/generic_amd64_go115.go
decoder/generic_amd64_go116.go
decoder/stubs.go
encoder/assembler_amd64_go115.go
encoder/assembler_amd64_go116.go
encoder/stubs.go

- behavior: projects build failed under 1.15 and reports "symbol listed multiple times"
- related issue: https://github.com/golang/go/issues/42401

fix: CANNOT support gcWriteBarrier due to linkname bug in go1.15

---

decoder/assembler_test.go
decoder/compiler.go
decoder/compiler_test.go
decoder/decoder.go
decoder/pools.go
encoder/compiler.go
encoder/encoder.go
issue_test/issue138_test.go
option/option.go
sonic.go

feat: Pretouch recursively for large/deep struct

---

internal/caching/fcache.go
issue_test/issue141_test.go

The priority of struct's fields in unmarshalling is as follows (in order of preference) [reference: https://go.dev/blog/json]: 
- An exported field with a matched tag
- An exported field  with a matched name
- The FRIST exported field with a case-insensitive matched tag or name.

fix: correct the field priority as encoding/json when unmarshal to struct

---

decoder/pools.go
encoder/encoder.go
encoder/pools.go

ps: remove `go:nosplit` compile directive for fake func

fix: keep arg `buf` alive

---

encoder/assembler_amd64_go115.go
encoder/assembler_amd64_go116.go
encoder/assembler_amd64_go117.go
encoder/encoder.go
encoder/encoder_test.go
encoder/primitives.go

- `NoCompactMarshaler` to avoid calling `json.Compace()` after encoding `json.Marshaler`
- `NoQuoteTextMarshler` to avoid calling `encodingString()` after encoding `encoding.TextMarshaler`
- `EscapeHTML` to call `json.EscapeHTML()` after serializing

feat:(encoder) add optimazing options

---

README.md
ast/encode_test.go
ast/parser.go
decoder/decoder.go
decoder/decoder_test.go
encoder/encoder.go
encoder/encoder_test.go
encoder/errors.go
encoder/primitives.go
internal/native/avx/native_amd64.go
internal/native/avx/native_amd64.s
internal/native/avx/native_amd64_test.go
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_amd64_test.go
internal/native/avx2/native_subr_amd64.go
internal/native/dispatch_amd64.go
internal/native/dispatch_amd64.s
internal/native/native_amd64.tmpl
internal/native/native_amd64_test.tmpl
internal/native/types/types.go
internal/rt/fastvalue.go
native/native.c
native/native.h
native/scanning.c
native/utf8.c
sonic.go

To support the FULL validation, add ValidateOne API in Golang.
The API can make more validations as follows:
1. check whether there are UNESCAPED control chars in JSON strings, e.g. "\"\n\b\"" is an invalid JSON string.
2. check whether the JSON strings are validated UTF-8. e.g. "\"\x80\"" is an invalid JSON string.
the validate is 2.5x faster of encoding/json(std library) :
```
➜  encoder git:(feat/validate) ✗ export SONIC_NO_ASYNC_GC=1 && go test -v -run none  -bench "(BenchmarkValidate_Sonic|BenchmarkSkip_Sonic|BenchmarkValidate_Std|BenchmarkCompact_Std)"
goos: darwin
goarch: amd64
pkg: github.com/bytedance/sonic/encoder
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkValidate_Sonic
BenchmarkValidate_Sonic-12         70855             16522 ns/op         788.93 MB/s …
```

support JSON validate

---

.github/workflows/codeql-analysis.yml
decoder/stream.go
decoder/stream_test.go

fix: (decoder) return io.EOF when read nothing from io.Reader

---

encoder/assembler_amd64_go116.go
encoder/assembler_amd64_go117.go
issue_test/issue258_test.go

fix:(encoder) handle map like pointer when calling `call_marshaler_v`

---

decoder/decoder_test.go
decoder/generic_amd64_go116.go
decoder/generic_amd64_go117.go

fix:(decoder) not check ',' before object key due to imperfect FSM

---

ast/node.go
ast/node_test.go

- `Int64()\Number()\Float64()` can cast `V_STRING` node to Go number, in consistence with other json AST libs including [json-iterator](https://github.com/json-iterator/go/blob/master/any_str.go#L95), [gjson](https://github.com/tidwall/gjson/blob/master/gjson.go#L118)

feat: (ast) support casting `V_STRING` to number

---

decoder/stream.go
decoder/stream_test.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
issue_test/issue263_test.go
native/scanning.c

skip return `ERR_EOF` error instead of `ERR_INVAL` when …run out buffer

fix:(native) `StreamDecoder` returns error when run out of buffer while skiping value

---

encoder/assembler_amd64_go116.go
encoder/assembler_amd64_go117.go
encoder/assembler_test.go

- since Go runtime always allocates memory of JIT stack `_Stack` right after that of output buffer `buf`:
- `_OP_i32` has a boundary check of size 11, but in native-C code,  when the integer is bigger than 99999999, the program will use `vmovdqu      %xmm0, (%rdi)` instruction to write a 16-byte chars into `buf` and cross the bound of it
- once buffer has no space more than 16B,  out-of-range memory writing can cause the corruption of `_Stack`, which finally causes abnormal behaviors of the program
Here is reproducible codes:
```
func TestEncoderMemoryCorruption(t *testing.T) {
var m = map[string]interface{}{
"1": map[string]interface{} {
`"`+strings.Repeat("a", _MaxBuffer - 38)+`"`: "b",
"1": map[string]int32{
"b": 1658219785,
},
},
}
out, err := Encode(m, SortMapKeys)
if err != nil { …
```

fix:(encoder) insufficient buffer size check for `OP_i32`

---

.github/workflows/push-check-arm.yml
README.md
compat.go

change push-check-arm.yml and remove fall back logics for Mac M1

change push-check-arm.yml and remove fall back logics

---

ast/iterator.go
ast/iterator_test.go

Traversal a empty object with HasNext() will cause a panic.
Reproduce bug, in ast/iterator_test.go
str, _ := getTestIteratorSample(0)
root, err := NewParser(str).Parse()
if err != 0 {
t.Fatal(err)
}
mi, _ := root.Get("object").Properties()
if mi.HasNext() {
t.Fatalf("should not have next")
}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x143bf91]
goroutine 8 [running]:
testing.tRunner.func1.2({0x14af1a0, 0x189a320})
/usr/local/Cellar/go/1.19.1/libexec/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
/usr/local/Cellar/go/1.19.1/libexec/src/testing/testing.go:1399 +0x39f
panic({0x14af1a0, 0x189a320}) …

fix iterator traversal empty object panic

---

bench.py
decode_test.go
decoder/pools.go
encoder/encoder_test.go
encoder/pools.go
internal/native/avx/native_amd64.s
internal/native/avx2/native_amd64.s
internal/native/sse/native_amd64.s
internal/native/types/types.go
issue_test/pretouch_test.go
native/native.h
native/types.h

```
go: added golang.org/x/text v0.3.6
name                                        old time/op    new time/op    delta
UnmarshalConcrete/CanadaGeometry_Sonic-256     925µs ±15%     933µs ±14%    ~     (p=0.841 n=5+5)
UnmarshalConcrete/CitmCatalog_Sonic-256       5.43ms ± 4%    5.65ms ± 9%    ~     (p=0.310 n=5+5)
UnmarshalConcrete/GolangSource_Sonic-256      19.1ms ± 8%    20.2ms ± 9%    ~     (p=0.151 n=5+5)
UnmarshalConcrete/StringEscaped_Sonic-256      104µs ± 8%     107µs ± 3%    ~     (p=0.421 n=5+5)
UnmarshalConcrete/StringUnicode_Sonic-256     14.1µs ±19%    12.8µs ±24%    ~     (p=0.310 n=5+5)
UnmarshalConcrete/SyntheaFhir_Sonic-256       12.9ms ± 5%    13.1ms ± 6%    ~     (p=0.841 n=5+5)
UnmarshalConcrete/TwitterStatus_Sonic-256     2.55ms ± 5%    2.60ms ± 3%    ~     (p=0.548 …
```

opt: reduce memory pool size

---

README.md
bench.py
decode_test.go
decoder/assembler_amd64_go116.go
decoder/assembler_amd64_go117.go
decoder/assembler_test.go
decoder/compiler.go
decoder/decoder_test.go
decoder/errors.go
decoder/types.go
internal/native/types/types.go

- check first char of binding value if match binded type. If not, try to skip the whole value
- `-benchtime=100000x` `count=50`
```
name                           old time/op    new time/op    delta
Decoder_Binding_Sonic_Fast-16    27.5µs ± 2%    27.9µs ± 2%  +1.55%  (p=0.000 n=46+48)
Decoder_Binding_Sonic-16         30.8µs ± 2%    31.0µs ± 2%  +0.68%  (p=0.000 n=47+49)
name                           old speed      new speed      delta
Decoder_Binding_Sonic_Fast-16   474MB/s ± 2%   467MB/s ± 2%  -1.52%  (p=0.000 n=46+48)
Decoder_Binding_Sonic-16        424MB/s ± 2%   421MB/s ± 2%  -0.67%  (p=0.000 n=47+49)
name                           old alloc/op   new alloc/op   delta
Decoder_Binding_Sonic-16         27.3kB ± 0%    27.3kB ± 0%    ~     (p=0.499 n=49+48)
Decoder_Binding_Sonic_Fast-16 …
```

feat:(decoder) support skip mismatche-typed value

---

README.md

The current example for printing errors from the decoder is broken when stable v1.5.0 is used.
I updated the documentation to clarify that decoder.MismatchTypeError is new to v1.6.0. I have also fixed the missing brace for the example.

feat: reformat print error example and clarify v1.6.0 example

---

internal/rt/asm_amd64.s
internal/rt/gcwb.go

- as #310 mentioned, go traceback while calling native functions may cause sonic crash. Therefore we commit PR #342 to prevent this ahead. However, it will make profiling results inaccurate, especially when sonic is heavily used.
- Thus, we add an environmental variant `SONIC_STOP_PROFILING` to control if `StopProf` feature should open, which only works when this variant is not empty

feat: add env option `SONIC_STOP_PROFILING` to stop profiling on demands

---

ast/search_test.go
fuzz/ast_fuzz_test.go
fuzz/fuzz_test.go
internal/native/avx/native_amd64.s
internal/native/avx2/native_amd64.s
internal/native/sse/native_amd64.s
native/scanning.c

1. fixed out-of-bound for single unclosed string.
2. enhanced the ast fuzz test. we got from the random data directly,  and did not find any panics.
```
fuzz: elapsed: 1h11m38s, execs: 4174743 (102/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m41s, execs: 4174991 (83/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m44s, execs: 4175047 (19/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m47s, execs: 4177154 (702/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m50s, execs: 4177154 (0/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m53s, execs: 4178579 (475/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m56s, execs: 4180035 (485/sec), new interesting: 60 (total: 3216)
fuzz: elapsed: 1h11m59s, execs: 4181583 (516/sec), new …
```

fix(ast): out-of-bound for single unclosed string

---

ast/api_amd64.go
ast/search_test.go
internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
internal/native/sse/native_amd64.s
internal/native/sse/native_subr_amd64.go
internal/native/types/types.go
native/scanning.c
native/types.h

return ErrorNoExist when the key or index is not found for GetFromString API.

fix: export not found error in ast get

---

decoder/compiler.go
decoder/decoder.go
internal/rt/fastvalue.go
issue_test/issue379_test.go

Try to fix #379.
1. Deal with the defined pointer type (elem with marshaler methods) as encoding/json.
2. Not inline when compiling the pointer.

fix: unmarshal into defined ptr type

---

decoder/assembler_amd64_go116.go
decoder/assembler_amd64_go117.go
issue_test/issue406_test.go

Fixed #406 .
To support skipped mismatched-type JSON value in decoding as encoding/json. (relative PR #325 )

fix: check mismatch error after recursive

---

internal/native/avx/native_amd64.s
internal/native/avx/native_subr_amd64.go
internal/native/avx2/native_amd64.s
internal/native/avx2/native_subr_amd64.go
internal/native/sse/native_amd64.s
internal/native/sse/native_subr_amd64.go
native/fastbytes.c

performance:
```
cpu: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
│ /tmp/tmphc12qb39.source.txt │    /tmp/tmp6sv5jjce.target.txt     │
│           sec/op            │   sec/op     vs base               │
Decoder_Generic_Sonic-8                                 278.0µ ± 4%   264.3µ ± 3%  -4.93% (p=0.001 n=10)
Decoder_Generic_Sonic_Fast-8                            211.6µ ± 4%   205.1µ ± 4%  -3.09% (p=0.023 n=10)
Decoder_Binding_Sonic-8                                105.03µ ± 4%   99.42µ ± 3%  -5.35% (p=0.000 n=10)
Decoder_Binding_Sonic_Fast-8                            83.17µ ± 5%   75.23µ ± 4%  -9.54% (p=0.000 n=10)
Decoder_Parallel_Generic_Sonic-8                        56.05µ ± 3%   54.35µ ± 2%  -3.04% (p=0.001 n=10)
Decoder_Parallel_Generic_Sonic_Fast-8                   43.87µ ± 4% …
```

opt: skip space use shuffle SIMD instruction

---

decoder/assembler_amd64_go116.go
decoder/assembler_amd64_go117.go
decoder/decoder_test.go

As #325.
Initialize the elem when slice grow in decode, so that the elem is the default value when mismatching type.

fix: initialize the elem when slice grow in decode

---

internal/decoder/assembler_amd64_go116.go
internal/decoder/assembler_amd64_go117.go

In some os, pointer of global var may be large imm64, so should not use `cmp reg, imm` instruction.
Fixed #435

fix: invalid cmpeq instruction in winos

---

Makefile
native/unittest/test_fastfint.c

Add unittest example for native C code.
We can put our specific C unittest in a single file, for example `test_xx.c`, and put it into the `./native/unittest`.
In the unittest, we can use any glibc functions.
just `make`

test: add unittest for native C code

---

internal/encoder/encoder.go

fix: internal.encoder.Pretouch only first opt effective

---

README.md
README_ZH_CN.md
ast/api_amd64.go
ast/api_compat.go
ast/decode.go
ast/node_test.go
ast/parser.go
decoder/decoder_compat.go
internal/decoder/decoder.go
internal/decoder/pools.go
internal/native/types/types.go

```
name                                     old time/op    new time/op    delta
LoadNode_Parallel/LoadAll()-16             6.08µs ± 4%    5.76µs ±26%     ~     (p=0.203 n=8+10)
LoadNode_Parallel/Load()-16                1.80µs ± 3%    2.02µs ±22%     ~     (p=0.055 n=10+10)
LoadNode/Load()-16                         5.54µs ± 5%    5.16µs ± 2%   -6.97%  (p=0.000 n=10+10)
LoadNode_Parallel/InterfaceUseNode()-16    2.91µs ± 5%    2.68µs ±16%   -7.80%  (p=0.003 n=10+9)
LoadNode/InterfaceUseNode()-16             6.77µs ± 4%    6.22µs ± 4%   -8.18%  (p=0.000 n=10+9)
LoadNode_Parallel/Interface()-16           12.1µs ± 2%    10.3µs ± 4%  -14.36%  (p=0.000 n=6+10)
LoadNode/LoadAll()-16                      13.6µs ± 8%    11.5µs ±10%  -15.28%  (p=0.000 n=10+10)
LoadNode/Interface()-16 …
```

opt:(ast) pass `skipnumber` flag to avoid decoding numbers

---

ast/encode_test.go
ast/parser_test.go
ast/search_test.go
decoder/decoder_test.go
encoder/encoder_test.go

The linter complains: the goroutine calls T.Fatal, which must be called in the same goroutine as the testSA2002(default).
testing.T.Fail will calls testing.common.FailNow(), this function will marks the test failing and call runtime.GoExit(). Sure, it could let the calling goroutine exit, but this is a misuse.
t.Fail should be used for marks the test failing and let the goroutine which runs this test or the benchmark func exit. So, just use t.Error+return instead.

fix/test: t.Fatal should be called from `g` running the test or benchmark func

---

scripts/go_latest.sh

Update go_latest.sh to fix a error

ci: update go_latest.sh

---

api.go
encoder/encoder_amd64.go
encoder/encoder_compat.go
internal/encoder/encoder.go
internal/encoder/primitives.go
sonic.go

NoValidateJSONMarshaler indicates that the encoder should not validate the output string after encoding the JSONMarshaler to JSON.

feat: Add NoValidateJSONMarshaler option

---

internal/encoder/compiler.go
issue_test/issue539_test.go

fix: checked if a interface is empty by its value field instead of type field

---

ast/iterator.go
ast/node.go
ast/node_test.go

After `Unset()` some nodes for its parent, call parent.Interface() will return errors like `unsupported type`
That's because since # , sonic/ast didn't delete node memory after `Unset()` meanwhile `Interface()` logic counted the actually non-exist node

fix: didn't pass non-exist value when call `Node.Interface()`

---

fuzz/fuzz_test.go
fuzz/other_fuzz_test.go
internal/decoder/stream.go
internal/decoder/stream_test.go

- refactor implementation of `StreamDecoder.Decode()`
- reduce memory copy by limiting start and end of slice passed to `skip()` 
- never move head of decoder buffer, always move tail
- check if buffer remains valid bytes after each`Decode()` or `More()`, if not, recycle buffer
```
name                          old time/op    new time/op    delta
DecodeStream_Sonic/halt-16       698µs ± 7%     732µs ± 3%   +4.84%  (p=0.002 n=10+10)
DecodeStream_Sonic/single-16     273µs ± 7%     191µs ± 4%  -30.03%  (p=0.000 n=9+10)
DecodeStream_Sonic/4x-16        1.49ms ± 2%    0.59ms ± 7%  -59.98%  (p=0.000 n=10+10)
DecodeStream_Sonic/double-16     679µs ± 3%     237µs ± 5%  -65.00%  (p=0.000 n=10+9)
DecodeStream_Sonic/small-16     27.0µs ± 8%     1.6µs ± 3%  -94.17%  (p=0.000 n=10+9)
name …
```

opt: refactor streaming decoder to fully use buffer

---

loader/stubs.go
loader/stubs_test.go

- Register new modules in a lockfree way to improve performance and avoid conflict with other libraries
> $ cd loader && go test -race -run=Test_registerModuleLockFree
> Begin GC looping...
> PASS
> ok      github.com/bytedance/sonic/loader       1.396s

opt: use lockfree to register new modules

---

api.go
encoder/encoder_amd64.go
encoder/encoder_compat.go
internal/encoder/encoder.go
internal/encoder/stream.go
sonic.go

Adds an option which allows to not write that extra newline between each message.

Allow the disabling of the newline in the encoder

---

loader/mmap_unix.go

build: perfect build tag for mmap_unix.go

---

ast/buffer.go
ast/buffer_test.go
ast/encode.go
ast/iterator.go
ast/iterator_test.go
ast/node.go
ast/node_test.go
ast/parser.go

- Before v1.9.2, `ast.Node.Unset()` will hard delete child for one node. But since #464 introduced llnked-chunk as storage, the behavior changed: `Unset()` will set an empty node at the index but still count it. This inconsistency disturbs our users, although current behavior sounds more reasonable as`Unset()`. Thus, we decide to be compatible with the old behavior.
- Besides, `UnsetByIndex()` is not a behavior provided by std `slice`, we recommend users to use `Add()` and `Pop()` instead
- `Len()` and `Index()` won't count emtpy nodes, as implemenation of `soft-delete`, which comes with overhead of index query O(N)
- Add `Pop()`, `Move()` API as `slice-like` OP

fix:(ast) implement soft delete for `Unset()` 

---

.github/workflows/codeql-analysis.yml
README.md
README_ZH_CN.md

doc: add API doc link

---

ast/node.go
ast/node_test.go

feat: add new node method "IndexOrGetWithIdx"

---

ast/buffer.go
ast/node.go
ast/node_test.go

```
func TestNodeSortKeys2(t *testing.T) {
root, err := NewSearcher(_TwitterJson).GetByPath()
if err != nil {
t.Fatal(err)
}
t.Run("single", func(t *testing.T) {
r := root.Get("statuses")
if r.Check() != nil {
t.Fatal(r.Error())
}
require.NoError(t, root.SortKeys(false))
})
t.Run("recurse", func(t *testing.T) {
require.NoError(t, root.SortKeys(true))
})
}
```
```
--  runtime error: invalid memory address or nil pointer dereference 
```
`sortKey()` use `unsafeMap()` at the beginning , which doesn't consider`V_RAW` type nodes

fix:(ast) SortKeys(true) panic when not loaded-all

---

internal/encoder/assembler_stkabi_amd64.go
issue_test/issue634_test.go

fix: possible oom when encode parallel in go1.16

---

ast/decode.go

Add a friendly compile error info for  #628 and #631

fix: better compile error info in 32-bit arch

---

ast/visitor.go
ast/visitor_test.go

https://github.com/bytedance/sonic/issues/653

fix(visitor): unconsumed rbrace in (*traverser).decodeObject()

---

.github/workflows/unit_test-linux-x64.yml
encoder/encoder_test.go
internal/encoder/encode_norace.go
internal/encoder/encode_race.go
internal/encoder/encoder.go
internal/encoder/encoder_norace_test.go
internal/encoder/encoder_test.go
issue_test/issue634_test.go
issue_test/race_test_go
scripts/test_race.sh

Enhance the data race detection when using Sonic JIT.
Problem: when running JIT codes, it will not generate race read/write even though enabling `-race`, and it will cause some data race cannot be detected.
Solution: We use encoding/json logic at first to make data race detection always work.

test: enhance data race detection

---

api.go
api_test.go

chore: export MarshalIndent api in root

---

README.md
README_ZH_CN.md
ast/encode.go
internal/decoder/api/stream.go
internal/encoder/encode_race.go
internal/encoder/encoder.go
internal/encoder/stream.go
internal/encoder/vars/stack.go
internal/rt/fastmem.go
option/option.go

opt: add limit on reusing buffer size

---

ast/error.go
internal/decoder/errors/errors.go
internal/encoder/vars/errors.go

chore: add more friendly warnings

---

api.go
compat.go
sonic.go

We need to identify the current strategy, whether it is std-json or sonic, to implement a wrapper in our library. This wrapper will issue a warning if upgrading go.mod in a user's project downgrades from sonic to std-json. Our goal is to avoid this situation.

add APIKind to indicate std-json or sonic

---

.github/workflows/unit_test-linux-x64.yml
scripts/test_pcsp.py

Follow-up: #688 
It shows that `linkname` are used in the PCSP test. This PR disables `linkname` checking under Go 1.23 to make the unit test work again.
It's a hotfix which seems not elegant. Marked as a draft.

fix: skip checking linkname when running PCSP test

---

internal/decoder/jitdec/assembler_regabi_amd64.go
internal/decoder/jitdec/generic_regabi_amd64.go
internal/decoder/jitdec/pools.go
issue_test/issue692_test.go
loader/loader_latest.go

Pin mismatch type error in `ST stack`, prevent it being collected by GC. Fixed #692

fix: corrupted mismatch type error in jit

---

decode_test.go
rawmessage.go

```
goos: linux
goarch: amd64
pkg: github.com/bytedance/sonic
cpu: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
BenchmarkDecoderRawMessage/StdRawMessage-8             75050         17134 ns/op     180.34 MB/s        7800 B/op         47 allocs/op
BenchmarkDecoderRawMessage/NocopyRawMessage-8          86970         12628 ns/op     244.69 MB/s        4987 B/op         26 allocs/op
BenchmarkDecoderRawMessage/NocopyRawMessageWithoutValidation-8            119670          9084 ns/op     340.18 MB/s        4893 B/op         26 allocs/op
PASS
```

opt: support NoCopyRawMessage

---

internal/decoder/jitdec/assembler_regabi_amd64.go
internal/decoder/jitdec/compiler.go
internal/decoder/optdec/compiler.go
internal/decoder/optdec/errors.go
internal/decoder/optdec/functor.go
internal/encoder/compiler.go
internal/encoder/ir/op.go
internal/encoder/pools_amd64.go
internal/encoder/vars/errors.go
internal/encoder/vm/vm.go
internal/encoder/x86/assembler_regabi_amd64.go
issue_test/common_test.go
issue_test/issue491_test.go
issue_test/issue755_test.go

fix
en: 
zh(optional): 
Fixes #491,  Fixes #554

fix bug when serde with unsupported type

---

ast/api_compat.go
decoder/decoder_compat.go
encoder/encoder_compat.go

Prevents polluting stdout in user code.

fix: Write version warning to stderr

---

internal/compat/warn.go

`&& CPU arm64 CPU` -> `&& arm64 CPU`

fix(compat): duplicate description

---

internal/encoder/alg/spec.go
internal/encoder/alg/spec_test.go
issue_test/biz_test.go
testdata/twitter.go

en: according to benchmark, `strconv.AppendItn()` has better performance than native implementation in `alg.I64toa`:
```
goos: darwin
goarch: arm64
pkg: github.com/bytedance/sonic/internal/encoder/alg
cpu: Apple M3 Pro
BenchmarkI64toa/sonic-1-12              48961936                22.01 ns/op            0 B/op          0 allocs/op
BenchmarkI64toa/std-1-12                329461662                3.600 ns/op           0 B/op          0 allocs/op
BenchmarkI64toa/sonic-16-12             55322376                21.48 ns/op            0 B/op          0 allocs/op
BenchmarkI64toa/std-16-12               438972664                2.730 ns/op           0 B/op          0 allocs/op
BenchmarkI64toa/sonic-256-12            55268763                21.42 ns/op            0 B/op          0 allocs/op …
```

opt:(encoder) use std `strconv.AppendInt` for better performance on arm

---

ast/node.go

A typo in node.go doc comment.
It is small but it is about method name, so I created this PR.

fix: typo in ast/node.go doc comment

---

internal/encoder/encoder_test.go
internal/encoder/vars/errors.go
internal/encoder/x86/assembler_regabi_amd64.go

feat: show JSON trace when panic

---

internal/encoder/compiler.go
internal/encoder/compiler_test.go
internal/encoder/pools_amd64.go
internal/encoder/pools_amd64_test.go

Related to https://github.com/bytedance/sonic/issues/842
Make encoder pretouch more similar to decoder
https://github.com/bytedance/sonic/issues/842
-

fix: make encoder pretouch able to recurse
